spring.application.name=apigateway
server.port=8080

# --- Eureka ---

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- Flota ---
spring.cloud.gateway.routes[0].id=flota
spring.cloud.gateway.routes[0].uri=lb://flota
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/flota/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# --- Logistica ---
spring.cloud.gateway.routes[1].id=logistica
spring.cloud.gateway.routes[1].uri=lb://logistica
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/logistica/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

# --- Seguridad ---

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/tpi-backend
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/tpi-backend/protocol/openid-connect/certs

eureka.instance.prefer-ip-address=true

# 2. IMPORTANTE: Forzamos manualmente a que la IP sea localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1

# 3. Define el ID de instancia para que no use el nombre de la PC
# Esto hace que en Eureka se vea como: flota:8082
eureka.instance.instance-id=${spring.application.name}:${server.port}