# --- Nombre de la Aplicación ---
spring.application.name=flota

# --- Puerto del Servidor ---
server.port=8082

# --- Eureka ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- Configuración de Base de Datos (POSTGRESQL) ---
# Asegúrate de crear la base de datos "db_flota" en tu pgAdmin o consola primero.
spring.datasource.url=jdbc:postgresql://localhost:5432/db_flota
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración de JPA / Hibernate para PostgreSQL ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# "update": Actualiza el esquema si cambia el código, pero MANTIENE los datos.
# Si prefieres que borre todo al reiniciar (como hacías en H2), usa "create-drop".
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SEGURIDAD KEYCLOAK (Resource Server) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/tpi-backend
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/tpi-backend/protocol/openid-connect/certs


eureka.instance.prefer-ip-address=true

# 2. IMPORTANTE: Forzamos manualmente a que la IP sea localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1

# 3. Define el ID de instancia para que no use el nombre de la PC
# Esto hace que en Eureka se vea como: flota:8082
eureka.instance.instance-id=${spring.application.name}:${server.port}