# El nombre del servicio
spring.application.name=eureka-server

# El puerto estandar de Eureka
server.port=8761

# Le dice al servidor que NO se registre a si mismo como un cliente
eureka.client.register-with-eureka=false

# Le dice al servidor que NO intente buscar otros servidores
eureka.client.fetch-registry=false
# --- CORRECCIÓN DE EUREKA (Agregar esto al final) ---

# 1. Obliga a usar la dirección IP en lugar del nombre de host
eureka.instance.prefer-ip-address=true

# 2. (Opcional pero recomendado) Fuerza el hostname a localhost para desarrollo local
eureka.instance.hostname=localhost